CREATE TABLE IF NOT EXISTS PROGRAMMES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
    
);

CREATE TABLE IF NOT EXISTS STUDENTS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    programme_id INTEGER NOT NULL,
    FOREIGN KEY (programme_id) REFERENCES PROGRAMMES(id)
   
);
CREATE TABLE IF NOT EXISTS COURS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL
   
);

CREATE TABLE IF NOT EXISTS INSCRIPTIONS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    student_id INTEGER NOT NULL,
    cours_id INTEGER NOT NULL,
    note REAL,
    UNIQUE (student_id, cours_id),
    FOREIGN KEY (student_id) REFERENCES STUDENTS(id),
    FOREIGN KEY (cours_id) REFERENCES COURS(id)
);

